app = "dlin-uptime-kuma"
primary_region = "ord"

[build]
  image = "louislam/uptime-kuma:2"

[[mounts]]
  source = "uptime_kuma_data"
  destination = "/app/data"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
